#!/usr/bin/env bash 

# VARIABLES
USERNAME="$1"
SG_PORT="22"
SSH_KEYS_PATH="$HOME/.ssh"
CONFIG_FILE="$HOME/.ssh-ec2.config"
PATH_HOME_USER="/home/$USER"
PEM_NAME=""
PEM_PATH=""
INSTANCE_NAME=""
INSTANCE_SG=""
AWS_PROFILE=""
ADDING_RULE=""
AWS_TAG1="Name"
AWS_TAG2=""
# Colors
bold=$(tput bold)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
red=$(tput setaf 1)
reset=$(tput sgr0)

# Creating file to save info session
if [ ! -e "$CONFIG_FILE" ]; then
    touch "$CONFIG_FILE"
    jq --arg key0   'last_ssh_keys_path' \
    --arg value0 '' \
    --arg key1   'last_aws_profile' \
    --arg value1 '' \
    --arg key2   'last_instance_name' \
    --arg value2 '' \
    --arg key3   'last_aws_pem' \
    --arg value3 '' \
    --arg key4   'tag1' \
    --arg value4 '' \
    --arg key5   'tag2' \
    --arg value5 '' \
    '. | .[$key0]=$value0 | .[$key1]=$value1 | .[$key2]=$value2 | .[$key3]=$value3 | .[$key4]=$value4 | .[$key5]=$value5' \
    <<<'{}' > $CONFIG_FILE

    CONFIG_FILE_JSON=$(cat $CONFIG_FILE)
    jq ".last_ssh_keys_path = \"$SSH_KEYS_PATH\"" <<<"$CONFIG_FILE_JSON" > $CONFIG_FILE
fi

echo ""
clear

if [ "$#" -ne 1 ]; then
    printf "\n${red}ERROR${reset}: script needs an argument: for more information run <${yellow}ec2-user -h${reset}>"
    echo ""
    exit -1
else
    if [ "$1" == "-h" ] || [ "S1" == "--help" ]; then
        echo "${bold}----------${reset}"
        printf "${bold}${green}Info${reset}\nScript needs an argument:"
        printf "\n1 - The ec2 ${bold}${green}username${reset} for ssh connection, usually: ${yellow}ubuntu${reset} if you are using Ubuntu SO in ec2 or ${yellow}ec2-user${reset} for Elastic Beanstalk."
        printf "\n2 - Configure: ${bold}${green}ssh-ec2 -c ${reset}or ${bold}${green}ssh-ec2 --configure${reset}"
        printf "\n3 - Help: ${bold}${green}ssh-ec2 -h ${reset}or ${bold}${green}ssh-ec2 -help${reset}"
        echo ""
        echo "${bold}----------${reset}"
        exit 0
    elif [ "$1" == "-c" ] || [ "$1" == "--configure" ]; then
        printf "\n########################################"
        echo "${yellow}"
        printf "\n             CONFIGURING                "
        echo "${reset}"
        printf "\n########################################"
        echo ""
        printf "${yellow}\n1. Where are key or pem file path located? (defaul path ~/.ssh): ${reset}"
        read SSH_KEYS_PATH
        if [ "$SSH_KEYS_PATH" == "" ]; then
            SSH_KEYS_PATH="$HOME/.ssh"
        fi
        printf "${yellow}\n2. Write one AWS instance tag name different to 'Name' to identify your instance (Leave empty if you do not need more): ${reset}"
        read AWS_TAG2
        CONFIG_FILE_JSON=$(cat $CONFIG_FILE)
        jq ".tag2 = \"$AWS_TAG2\"" <<<"$CONFIG_FILE_JSON" > $CONFIG_FILE
        CONFIG_FILE_JSON=$(cat $CONFIG_FILE)
        jq ".tag1 = \"$AWS_TAG1\"" <<<"$CONFIG_FILE_JSON" > $CONFIG_FILE
        exit 0
    fi
fi

echo ""

# Getting last configuration
AWS_TAG1=$(cat $CONFIG_FILE | jq .tag1 | sed 's/"//g')
AWS_TAG2=$(cat $CONFIG_FILE | jq .tag2 | sed 's/"//g')
if [ "$AWS_TAG1" == "" ]; then
    echo "${red}ERROR${reset}: First configure your perfil"
    echo "Run ${green}ssh-ec2 -c ${reset}or ${green}ssh-ec2 --configure${reset}"
    exit -1
fi
LAST_SSH_KEYS_PATH=$(cat $CONFIG_FILE | jq .last_ssh_keys_path | sed 's/"//g')
LAST_AWS_PROFILE=$(cat $CONFIG_FILE | jq .last_aws_profile | sed 's/"//g')
LAST_PEM_NAME=$(cat $CONFIG_FILE | jq .last_aws_pem | sed 's/"//g')
LAST_INSTANCE_NAME="$(cat $CONFIG_FILE| jq .last_instance_name | sed 's/"//g')"

# Check if config file is writable
if [ ! -w "$CONFIG_FILE" ]; then
    echo "${red}ERROR: configuration file located in $HOME/.ssh-ec2.config is not writable.${reset}"
    exit -1
fi

# Choose your AWS profile
printf "\n#######################################"
echo "${yellow}"
printf "\n             AWS PROFILE                "
echo "${reset}"
printf "\n#######################################"
printf "\n\n"
grep -A 0 "\[" ~/.aws/credentials | sed 's/\[//' | sed 's/\]//'
printf "\n${yellow}Which AWS profile ($LAST_AWS_PROFILE): ${reset}"
read AWS_PROFILE

# Setting conf file
if [ "$AWS_PROFILE" == "" ]; then
    AWS_PROFILE="$LAST_AWS_PROFILE"
else
    CONFIG_FILE_JSON=$(cat $CONFIG_FILE)
    jq ".last_aws_profile = \"$AWS_PROFILE\"" <<<"$CONFIG_FILE_JSON" > $CONFIG_FILE
fi

# Getting instances tags name
echo ""
printf "\n#######################################"
echo "${yellow}"
printf "\n             INSTANCE NAME              "
echo "${reset}"
printf "\n#######################################"
printf "\n\n"

if [ "$AWS_TAG2" == "" ]; then
    aws --profile $AWS_PROFILE ec2 describe-instances --query \
    "Reservations[*].Instances[*].{$AWS_TAG1: Tags[?Key=='"$AWS_TAG1"'] | \
    [0].Value, State: State.Name, PEM_in_AWS: KeyName}" \
    --output table | awk '/running/ { $0 = "\033[32m" $0 "\033[32m" }; /stopped/ { $0 = "\033[31m" $0 "\033[31m" }; 1'
else 
    aws --profile $AWS_PROFILE ec2 describe-instances --query \
    "Reservations[*].Instances[*].{$AWS_TAG1: Tags[?Key=='"$AWS_TAG1"'] | \
    [0].Value, $AWS_TAG2: Tags[?Key=='"$AWS_TAG2"'] | \
    [0].Value, State: State.Name, PEM_in_AWS: KeyName}" \
    --output table | awk '/running/ { $0 = "\033[32m" $0 "\033[32m" }; /stopped/ { $0 = "\033[31m" $0 "\033[31m" }; 1'
fi

printf "\n${yellow}Which ec2 label $AWS_TAG1 ($LAST_INSTANCE_NAME): ${reset}"
read INSTANCE_NAME

## Setting conf file
if [ "$INSTANCE_NAME" == "" ]; then
    INSTANCE_NAME="$LAST_INSTANCE_NAME"
else
    CONFIG_FILE_JSON=$(cat $CONFIG_FILE)
    jq ".last_instance_name = \"$INSTANCE_NAME\"" <<<"$CONFIG_FILE_JSON" > $CONFIG_FILE
fi

# Getting public dns
PUBLIC_DNS=$(aws --profile $AWS_PROFILE ec2 describe-instances --query "Reservations[*].Instances[*].PublicDnsName" \
--output=text --filters "Name=tag-key,Values=Name" "Name=tag-value,Values=$INSTANCE_NAME")
# Getting pem name
INSTANCE_AWS_PEM=$(aws --profile $AWS_PROFILE ec2 describe-instances --query \
"Reservations[*].Instances[*].KeyName" --output text --filters \
"Name=tag-key,Values=Name" "Name=tag-value,Values=$INSTANCE_NAME")

# Getting the ssh kays ready in $home/.ssh
echo ""
printf "\n#######################################"
echo "${yellow}"
printf "\n        PEM NAME in your local          "
echo "${reset}"
printf "\n#######################################"
printf "\n"
echo "$(ls -l $SSH_KEYS_PATH | awk '{ print $9 }')"
echo "${red}---------------------------------------${reset}"
printf "Instance chosen: ${green}$INSTANCE_NAME${reset}, PEM recommended: ${green}${INSTANCE_AWS_PEM}.pem${reset}"
printf "\n${yellow}Write your pem name ($LAST_PEM_NAME): ${reset}"
read PEM_NAME

# Setting conf file
if [ "$PEM_NAME" == "" ]; then
    PEM_NAME="$LAST_PEM_NAME"
else
    CONFIG_FILE_JSON=$(cat $CONFIG_FILE)
    jq ".last_aws_pem = \"$PEM_NAME\"" <<<"$CONFIG_FILE_JSON" > $CONFIG_FILE
fi

PEM_PATH="$SSH_KEYS_PATH/$PEM_NAME"

# Getting SG id
INSTANCE_SG_ID=$(aws --profile $AWS_PROFILE ec2 describe-instances --query \
"Reservations[*].Instances[*].SecurityGroups[*].GroupId" --output=text --filters \
"Name=tag-key,Values=Name" "Name=tag-value,Values=$INSTANCE_NAME" "Name=instance-state-code,Values=16")
echo "${yellow}"
printf "\nSecurity Group id: $INSTANCE_SG_ID"
echo "${reset}"
echo ""

# Getting my public ip
MY_PUBLIC_IP=$(curl ipinfo.io/ip)
echo ""
# Openning SSH SG for your public ip
echo "Adding SG rule for your public ip..."
aws --profile $AWS_PROFILE ec2 authorize-security-group-ingress --group-id $INSTANCE_SG_ID --protocol tcp --port $SG_PORT --cidr ${MY_PUBLIC_IP}/32
ADDING_RULE="$?"

# SSH CONNECTION
echo ""
printf "\n#######################################"
echo "${yellow}"
printf "\n            SSH CONNECTION              "
echo "${reset}"
printf "\n#######################################"
printf "\n\n"

printf "Setting connection: \nssh -i $PEM_PATH $USERNAME@$PUBLIC_DNS\n\n"
echo ""
if [ "$PEM_PATH" == "" ] || [ "$USERNAME" == "" ] || [ "$PUBLIC_DNS" == "" ] ;then
    echo "${red}ERROR: some variable is empty:${reset}"
    printf "\n- ${red}Pem path${reset}: $PEM_PATH"
    printf "\n- ${red}Instance username${reset}: $USERNAME"
    printf "\n- ${red}Public dns${reset}: $PUBLIC_DNS"
    echo ""
    exit -1
fi
ssh -i $PEM_PATH $USERNAME@$PUBLIC_DNS

# DELETING SSH SG for your public ip
if [ "0" == "$ADDING_RULE" ]; then
	echo "Deleting SG rule for your public ip..."
	aws --profile $AWS_PROFILE ec2 revoke-security-group-ingress --group-id $INSTANCE_SG_ID --protocol tcp --port $SG_PORT --cidr ${MY_PUBLIC_IP}/32
fi

echo ""
echo "END"
